apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: frontend
        static_configs:
          - targets: ['frontend-service:80']
      - job_name: backend
        static_configs:
          - targets: ['backend-service:3000']
      - job_name: mongodb
        static_configs:
          - targets: ['mongodb-service:27017']
      - job_name: rabbitmq
        static_configs:
          - targets: ['rabbitmq-service:5672']